// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAW-8Sk8_le31wC1r-wqZy4joYSOMNwYFA',
    appId: '1:349090519916:web:ebae0c2fa3f4c7a6153149',
    messagingSenderId: '349090519916',
    projectId: 'e-commerce-app-clot',
    authDomain: 'e-commerce-app-clot.firebaseapp.com',
    storageBucket: 'e-commerce-app-clot.firebasestorage.app',
    measurementId: 'G-1GNCJ6PMS4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2vnVGQ59uwNSr46e4motPnfWXCcpFHws',
    appId: '1:349090519916:android:8c638921fd163add153149',
    messagingSenderId: '349090519916',
    projectId: 'e-commerce-app-clot',
    storageBucket: 'e-commerce-app-clot.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgYMtZg2n6Nc8X21HQw_NqxH2kni2feXg',
    appId: '1:349090519916:ios:a47777899fc187de153149',
    messagingSenderId: '349090519916',
    projectId: 'e-commerce-app-clot',
    storageBucket: 'e-commerce-app-clot.firebasestorage.app',
    iosBundleId: 'com.example.eCommerceClot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgYMtZg2n6Nc8X21HQw_NqxH2kni2feXg',
    appId: '1:349090519916:ios:a47777899fc187de153149',
    messagingSenderId: '349090519916',
    projectId: 'e-commerce-app-clot',
    storageBucket: 'e-commerce-app-clot.firebasestorage.app',
    iosBundleId: 'com.example.eCommerceClot',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAW-8Sk8_le31wC1r-wqZy4joYSOMNwYFA',
    appId: '1:349090519916:web:5d63be46ae1d178e153149',
    messagingSenderId: '349090519916',
    projectId: 'e-commerce-app-clot',
    authDomain: 'e-commerce-app-clot.firebaseapp.com',
    storageBucket: 'e-commerce-app-clot.firebasestorage.app',
    measurementId: 'G-SPS6E38G47',
  );
}
